DEBUG = True
SECRET_KEY = 'bed026e0567e203d20527449faf89eb6f503e772dd319622559b31852a7b'
MAIL_SERVER = 'smtp.gmail.com'        # Servidor SMTP
MAIL_PORT = 587                         # Puerto SMTP
MAIL_USE_TLS = True                     # Usar TLS (Transport Layer Security)
MAIL_USE_SSL = False                    # No usar SSL (Secure Sockets Layer)
MAIL_USERNAME = 'williamandresariasherrera2@gmail.com' # Tu correo electrónico
MAIL_PASSWORD = 'Meggabass489'    # Tu contraseña de correo electrónico
MAIL_DEFAULT_SENDER = 'williamandresariasherrera2@gmail.com' # Remitente por defecto